{
  "name": "Staff Assignment Manager",
  "client_id": "e33dee3eb5ba764d24d3064d6a070c11",
  "application_url": "https://shopify-staff-assignment-evas1antm.vercel.app",
  "embedded": true,
  "access_scopes": {
    "scopes": "read_companies,write_companies"
  },
  "webhooks": {
    "api_version": "2025-01"
  },
  "pos": {
    "embedded": false
  }
}
